[phases.setup]
nixPkgs = ["python311"]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python migrate_with_retry.py && python create_admin.py && gunicorn school_project.wsgi --bind 0.0.0.0:$PORT --log-file - --timeout 120 --workers 2 --access-logfile - --error-logfile -"
